### ISSUE TITLE
Currently lost track of releases

### ISSUE THREAD

**Issue by mxmxchere** [gardener/etcd-custom-image#30]
**What would you like to be added**:
The current version of etcd is v3.5.6 (https://github.com/etcd-io/etcd/blob/main/CHANGELOG/CHANGELOG-3.5.md#v356-2022-11-21). The latest gardener releases version of etcd is v3.5.2

**Why is this needed**:
Patches,Bugfixes, you name it :)

**Comment by renormalize** [comment]
@mxmxchere 

The Gardener organization has started moving away from making use of `etcd-custom-image` to [`etcd-wrapper`](https://github.com/gardener/etcd-wrapper).
I would recommend you do the same and open all future issues on that repository.

Why `etcd-wrapper`?
It gives the user far more flexibility and is significantly more robust than the shell script that is `etcd-custom-image`. [`etcd-druid`](https://github.com/gardener/etcd-druid) that is an operator of `etcd` clusters has improvements planned in the *near* future which rely on the functionality that `etcd-wrapper` provides - which I'm sure you would be interested in making use of.

As for the contents of the issue - we are currently working on upgrading `etcd` to a newer version, with a release for `etcd-wrapper` planned for some time in Q2 of this year.

**Comment by mxmxchere** [comment]
very good, thanks for reaching out :)
